### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by betharowan** [betharowan/TIGER_Scripts-for-distribution#11]
Vipul, can you make sure that the documentation in the README stays up-to-date with all of the changes that you have been making?

**Comment by Imoteph** [comment]
Yes, these are just bug fixes appearing with TIGER  appling on de-novo
assembly genomes, where the standard of input data is not the same as we
are used too.

2016-03-17 19:00 GMT+01:00 betharowan notifications@github.com:
